# Generated by Django 3.1 on 2020-08-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_auto_20200806_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='file',
            field=models.FileField(blank=True, max_length=254, upload_to='media/'),
        ),
    ]
