# Generated by Django 3.1 on 2020-08-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_coffee_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='coffee_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='file',
        ),
    ]
