# Generated by Django 3.1 on 2020-08-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0004_auto_20200806_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
