# Generated by Django 3.1 on 2020-08-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0005_coffee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee_file',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coffee_file',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee_file',
            name='csv_file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
