# Generated by Django 3.1 on 2020-08-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0006_auto_20200806_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee_file',
            name='csv_file',
            field=models.FileField(upload_to='media'),
        ),
    ]
